#@TYPE: Machine
#@NAME: KVM virtual machine
#@DESCRIPTION: Machine configuration for the http://linux-kvm.org virtual machine 

require include/rome.inc

MACHINEOVERRIDES =. "kvm:"

IMAGE_FSTYPES = "wic"

PRIMARY_NETIF = "enp0s18"
ROOT = "/dev/sda2"

EXTRA_IMAGEDEPENDS += "grub-efi grub-bootconf"
PREFERRED_PROVIDER_virtual/bootloader = "grub-efi"

MACHINE_EXTRA_RRECOMMENDS:remove = "linux-firmware"
MACHINE_EXTRA_RRECOMMENDS:append = " qemu-guest-agent"

MACHINE_ESSENTIAL_EXTRA_RDEPENDS:remove = "thermald"

