require conf/distro/voltumna.conf

DISTRO_NAME = "DS"
SDK_VENDOR = "-dssdk"
TARGET_VENDOR = "-ds"

# Necessary to add lapack
FORTRAN:forcevariable = ",fortran"
RUNTIMETARGET:append:pn-gcc-runtime = " libquadmath"
